'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Push2Run.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        '''    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''
        '''    &lt;Color x:Key=&quot;ThemeTop&quot;&gt;Azure&lt;/Color&gt;
        '''    &lt;Color x:Key=&quot;ThemeCentre&quot;&gt;White&lt;/Color&gt;
        '''
        '''    &lt;Color x:Key=&quot;ThemeEnabled&quot;&gt;Black&lt;/Color&gt;
        '''    &lt;Color x:Key=&quot;ThemeDisabled&quot;&gt;LightGray&lt;/Color&gt;
        '''
        '''    &lt;SolidColorBrush x:Key=&quot;SelectedForegroundBrush&quot; Color=&quot;SkyBlue&quot; /&gt;
        '''    &lt;SolidColorBrush x:Key=&quot;SelectedBackgroundBrush&quot; Color=&quot;PaleTurquoise&quot; /&gt;
        '''    &lt;SolidColorBru [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BrushResources() As String
            Get
                Return ResourceManager.GetString("BrushResources", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        '''                    xmlns:local=&quot;clr-namespace:Push2Run_boss&quot;
        '''    xmlns:s=&quot;clr-namespace:System;assembly=mscorlib&quot;                 
        '''    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''
        '''    &lt;ResourceDictionary.MergedDictionaries&gt;
        '''        &lt;ResourceDictionary Source=&quot;BrushResources.xaml&quot; /&gt;
        '''    &lt;/ResourceDictionary.MergedDictionaries&gt;
        '''
        '''    &lt;DataTemplate x:Key=&quot;HeaderTemplateArrowUp&quot;&gt;
        '''        &lt;DockPanel&gt;
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ControlResources() As String
            Get
                Return ResourceManager.GetString("ControlResources", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Push2Run() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Push2Run", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Push2Run_r() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Push2Run_r", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Push2Run_y() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Push2Run_y", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This directory contains a Push2Run database file and up to seven backups of the Push2Run database file.
        '''
        '''The Push2Run database file is named &apos;Push2Run.db3&apos;.
        '''
        '''The Push2Run database backup files are named &apos;Push2Run-1.db3&apos; to &apos;Push2Run-7.db3&apos;.
        '''
        '''The most recent backup file is named &apos;Push2Run-1.db3&apos;, the least recent backup file is named &apos;Push2Run-7.db3&apos;.
        '''
        '''If you don&apos;t see the &apos;.db3&apos; part of the filename then from the menu bar of Microsoft File Explorer click on &apos;View&apos;, and then check the option &apos;File na [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ReadMeDatabaseRestore() As String
            Get
                Return ResourceManager.GetString("ReadMeDatabaseRestore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This directory contains a Push2Run settings file and up to seven backups of the Push2Run settings file.
        '''
        '''The Push2Run settings file is named &apos;user.config&apos;.
        '''
        '''The Push2Run settings backup files are named &apos;user-1.config&apos; to &apos;user-7.config&apos;.
        '''
        '''The most recent backup file is named &apos;user-1.config&apos;, the least recent backup file is named &apos;user-7.config&apos;.
        '''
        '''If you don&apos;t see the &apos;.config&apos; part of the filename then from the menu bar of Microsoft File Explorer click on &apos;View&apos;, and then check the option &apos;File name [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ReadMeSettingRestore() As String
            Get
                Return ResourceManager.GetString("ReadMeSettingRestore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property switchoff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("switchoff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property switchon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("switchon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UACShield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UACShield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
